<?php

/**
 * Implements hook_menu().
 */
function payer_qiwi_menu() {
  $items = [];

  $items['admin/config/payer/qiwi'] = array(
    'title' => 'QIWI',
    'description' => 'Configure settings Payer QIWI.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'payer_qiwi_config_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

function payer_qiwi_config_page() {
  return 'QIWI';
}