<?php

/**
 * Implements hook_menu().
 */
function payer_menu() {
  $items = array();

  $items['admin/config/payer'] = array(
    'title' => 'Payer',
    'description' => 'Configure settings Payer.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'payer_config_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Обработчик страницы конфигурации модуля Payer
 **/
function payer_config_page() {
  $dir_methods = DRUPAL_ROOT . '/' . drupal_get_path('module', 'payer') . '/methods' ;
  // Поиск файлов .info по указанному пути.
  $existing_methods = file_scan_directory($dir_methods, '/.*\.info/');

  // Шапка таблицы с контентом
  $headers = array(
    array('class' => array('pay-method_status')),
    array('data' => 'Method'),
    array('data' => 'Operations'),
  );

  // Строки таблицы с контентом
  $rows = array();

  /**
   * Подготовка информации о имеющихся способах оплаты в папке "methods"
   */
  foreach($existing_methods as $pay_method) {
    $options = array(
      'config_link' => NULL, // ссылка на конфиг метода оплаты.
      'method_name' => NULL, // системное название метода.
      'description' => NULL, // описание метода.
      'image' => NULL, // изображение.
      'info' => NULL, // информация, содержащаяся в файле .info
      'status' => FALSE, // Флаг активности модуля
    );

    $options['info'] = drupal_parse_info_file($pay_method->uri);
    $options['method_name'] = $pay_method->name;
    $options['status'] = module_exists($options['method_name']) ? TRUE : FALSE;

    if(!$options['status']) {
      $options['description'] .= '<div class="messages warning">';
      $options['description'] .= t(
        'The payment method &quot;@pay_method&quot; is installed, but it is off. To use the module functionality, enable it on the !page_modules under &quot;Payment&quot;',
        array(
          '@pay_method' => $options['info']['name'],
          '!page_modules' => l(t('modules page'), 'admin/modules'),
        )
      );
      $options['description'] .= '</div>';
      $options['status'] = '🚫';
    }
    else {
      $options['config_link'] = l('Config', $options['info']['configure']);
      $options['status'] = '✅';
    }

    $options['image'] = drupal_get_path('module', $options['method_name']) . '/preview.png';

    if(file_exists($options['image'])) {
      $options['image'] = theme('image', array('path' => $options['image']));
    }
    else {
      $options['image'] = NULL;
    }

    $options['description'] .= '<h3>' . $options['info']['name'] . '</h3>';
    $options['description'] .= theme('default', array());;
    $options['description'] .= $options['image'];
    $options['description'] .= '<p>' . $options['info']['description'] . '</p>';

    // Добавление вычесленных данных в массив $rows
    $rows[$options['method_name']] = array(
      'data' => array(
        array(
          'data'  => $options['status'],
          'class' => array('pay-method_status')
        ),
        $options['description'],
        $options['config_link'],
      ),
    );
  }

  usort($rows, function($a, $b){
    if($a['data'][0]['data'] === $b['data'][0]['data'])
      return 0;

    return $a['data'][0]['data'] > $b['data'][0]['data'] ? 1 : -1;
  });

  // Сборка данных для страницы
  $page_data = array(
    'header' => $headers,
    'rows' => $rows,
    'sticky' => TRUE,
    'empty' => t('No results found'),
    'attributes' => array(),
    'caption' => FALSE,
    'colgroups' => array(),
  );

  return theme(
    'config_page_template',
    array('page_data' => $page_data)
  );
}

/**
 * Implement hook_theme().
 */
function payer_theme(){
  return array(
    'config_page_template' => array(
      // file name will be payer-config.tpl.php
      'template' => 'templates/payer-config',
      'variables' => array('page_data' => NULL),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function payer_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'events_pay_node_form') {
    if(
      !isset($form['#node']->events_pay_act)
      && !isset($form['#node']->events_pay_amount)
    ) {
      unset($form['title']);
      // Добавление валидации
      $form['#validate'][] = 'payer_validate_event_pay_node';
      // Полностью заменяем стандартный обработчик формы
      $form['actions']['submit']['#submit'] = array('payer_create_event_pay_node');
    }
    else {
      drupal_set_message(t('You can\'t edit an already created event'), 'warning');
      $form['title']['#disabled'] = TRUE;
      $form['events_pay_act']['#disabled'] = TRUE;
      $form['events_pay_amount']['#disabled'] = TRUE;
      $form['events_pay_comment']['#disabled'] = TRUE;
      $form['actions']['submit']['#access'] = FALSE;
    }
  }
}

/**
 * Валидация формы создания типа материала "events_pay"
 **/
function payer_validate_event_pay_node($form, &$form_state) {
  $act = $form_state['values']['events_pay_act']['und'][0]['value'];
  $amount = $form_state['values']['events_pay_amount']['und'][0]['value'];
  $user = user_load_by_name($form_state['values']['name']);
  $amount_wallet = field_get_items( 'user' , $user, 'payer_wallet' );
  $amount_wallet = $amount_wallet[0]['value'];

  if (isset($amount) && $act == 0 && ($amount_wallet - $amount) < 0) {
    form_set_error('events_pay_amount', t('Insufficient funds!'));
  }
}

/**
 * Обработчик формы создания типа материала "events_pay" после валидации
 **/
function payer_create_event_pay_node($form, &$form_state) {
  $user = user_load_by_name($form_state['values']['name']);
  $vars = array(
    'uid' => $user->uid,
    'act' => $form_state['values']['events_pay_act']['und'][0]['value'],
    'amount' => $form_state['values']['events_pay_amount']['und'][0]['value'],
    'comment' => $form_state['values']['events_pay_comment']['und'][0]['value'],
  );

  $event = new Payer($vars);
  $event->handler_event_pay();
}