<?php

/**
 * Implements hook_menu().
 */
function payer_robokassa_menu() {
  $items = [];

  $items['admin/config/payer/robokassa'] = array(
    'title' => 'Robokassa',
    'description' => 'Configure settings Payer robokassa.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'payer_robokassa_config_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

function payer_robokassa_config_page() {
  return 'Robokassa';
}