<?php

/**
 * Implements hook_menu().
 */
function payer_advanced_cash_menu() {
  $items = [];

  $items['admin/config/payer/free-kassa'] = array(
    'title' => 'Free kassa',
    'description' => 'Configure settings Payer Advanced Cash.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'payer_advanced_cash_config_page',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

function payer_advanced_cash_config_page() {
  return 'Advanced Cash';
}